package tarinatilasto;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;

/**
 * Test class made by ComTest
 * @version 2019.04.21 15:21:23 // Generated by ComTest
 *
 */
public class SarjaTest {



  // Generated by ComTest BEGIN
  /** testGetNimi44 */
  @Test
  public void testGetNimi44() {    // Sarja: 44
    Sarja testisarja = new Sarja(2, "Testing"); 
    assertEquals("From: Sarja line: 46", "Testing", testisarja.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi58 */
  @Test
  public void testRekisteroi58() {    // Sarja: 58
    Sarja huntik = new Sarja(); 
    assertEquals("From: Sarja line: 60", 0, huntik.getTunnusNro()); 
    huntik.rekisteroi(); 
    assertEquals("From: Sarja line: 62", 1, huntik.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetTunnusNro82 */
  @Test
  public void testGetTunnusNro82() {    // Sarja: 82
    Sarja testisarja = new Sarja(); 
    assertEquals("From: Sarja line: 84", 0, testisarja.getTunnusNro()); 
    testisarja.rekisteroi(); 
    assertEquals("From: Sarja line: 86", 2, testisarja.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString97 */
  @Test
  public void testToString97() {    // Sarja: 97
    Sarja sarja = new Sarja(); 
    sarja.parse("   9   |   Testinimi   "); 
    assertEquals("From: Sarja line: 100", "9|Testinimi", sarja.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse144 */
  @Test
  public void testParse144() {    // Sarja: 144
    Sarja sarja = new Sarja(); 
    sarja.parse("   8   |   Testi"); 
    assertEquals("From: Sarja line: 147", 8, sarja.getTunnusNro()); 
    assertEquals("From: Sarja line: 148", "8|Testi", sarja.toString()); 
    sarja.rekisteroi(); 
    int n = sarja.getTunnusNro(); 
    sarja.parse(""+(n+20)); 
    sarja.rekisteroi(); 
    assertEquals("From: Sarja line: 154", n+20+1, sarja.getTunnusNro()); 
  } // Generated by ComTest END
}